### ISSUE TITLE
一篇带你用 VuePress + Github Pages 搭建博客

### ISSUE THREAD

**Issue by mqyqingfeng** [mqyqingfeng/Blog#235]
## 前言

最近完成了 TypeScript 最新官方文档 Hanbook 的翻译，一共十四篇，堪称国内的最好 TypeScript4 入门教程之一[。](https://cdn.jsdelivr.net/gh/mqyqingfeng/picture/%E6%88%AA%E5%B1%8F2021-12-12%20%E4%B8%8B%E5%8D%883.12.02.png)为了方便大家阅读，我用 VuePress + Github Pages 搭建了博客，博客效果如下：

![](https://cdn.jsdelivr.net/gh/mqyqingfeng/picture/screen2.png)

![](https://cdn.jsdelivr.net/gh/mqyqingfeng/picture/screen1.png)

博客地址如下：

- Github [https://mqyqingfeng.github.io/learn-typescript/](https://mqyqingfeng.github.io/learn-typescript/)
- Gitee [http://mqyqingfeng.gitee.io/learn-typescript/](http://mqyqingfeng.gitee.io/learn-typescript/)

## 0. VuePress

VuePress 自然不用多说，基于 Vue 的静态网站生成器，风格简约，配置也比较简单。之所以不使用 [VitePress](https://vitepress.vuejs.org/)，是因为想使用现有的主题， 而 VitePress 不兼容当前 VuePress 的生态系统，至于为什么不选择 [VuePress@next](https://v2.vuepress.vuejs.org/zh/)，考虑到还处于 Beta 阶段，等稳定后再开始迁移。

## 1. 本地搭建

快速开始[同 VuePress 官网](https://vuepress.vuejs.org/zh/guide/getting-started.html)：

1. 创建并进入一个新目录

```shell
// 文件名自定义
mkdir vuepress-starter && cd vuepress-starter
```

2. 使用你喜欢的包管理器进行初始化

```shell
yarn init # npm init
```

3. 将 VuePress 安装为本地依赖

```shell
yarn add -D vuepress # npm install -D vuepress
```

4. 创建你的第一篇文档，VuePress 会以 docs 为文档根目录，所以这个 README.md 相当于主页：

```shell
mkdir docs && echo '# Hello VuePress' > docs/README.md
```

5. 在 package.json 中添加一些 scripts

```json
{
  "scripts": {
    "docs:dev": "vuepress dev docs",
    "docs:build": "vuepress build docs"
  }
}
```

6. 在本地启动服务器

```shell
yarn docs:dev # npm run docs:dev
```

VuePress 会在 [http://localhost:8080](http://localhost:8080) (opens new window) 启动一个热重载的开发服务器。

## 2. 基础配置

在文档目录下创建一个 `.vuepress` 目录，所有 VuePress 相关的文件都会被放在这里。此时你的项目结构可能是这样：

```typescript
.
├─ docs
│  ├─ README.md
│  └─ .vuepress
│     └─ config.js
└─ package.json
```

在 `.vuepress` 文件夹下添加 `config.js`，配置网站的标题和描述，方便 SEO：

```typescript
module.exports = {
  title: 'TypeScript4 文档',
  description: 'TypeScript4 最新官方文档翻译'
}
```

此时界面类似于：

![](https://cdn.jsdelivr.net/gh/mqyqingfeng/picture/1639294470973-2c0aa3ba-4c54-4cf1-bce4-cfbb2b07a028.png)

## 3. 添加导航栏

我们现在在页首的右上角添加导航栏，修改 `config.js`:

```typescript
module.exports = {
    title: '...',
    description: '...',
    themeConfig: {
        nav: [
            { text: '首页', link: '/' },
            { 
                text: '冴羽的 JavaScript 博客', 
                items: [
                    { text: 'Github', link: 'https://github.com/mqyqingfeng' },
                    { text: '掘金', link: 'https://juejin.cn/user/712139234359182/posts' }
                ]
            }
        ]
    }
}
```

效果如下：

![](https://cdn.jsdelivr.net/gh/mqyqingfeng/picture/1639294922655-f0241cb2-d7d1-4077-8349-2bf6ddf0b961.png)

更多的配置参考 [VuePress 导航栏](https://vuepress.vuejs.org/zh/theme/default-theme-config.html#%E5%AF%BC%E8%88%AA%E6%A0%8F)。

## 4. 添加侧边栏

现在我们添加一些 md 文档，目前文档的目录如下：

```shell
.
├─ docs
│  ├─ README.md
│  └─ .vuepress
│     └─ config.js
|  └─ handbook
|  	  └─ ConditionalTypes.md
|	    └─ Generics.md
└─ package.json
```

我们在 `config.js` 配置如下：

```typescript
module.exports = {
    themeConfig: {
        nav: [...],
        sidebar: [
            {
                title: '欢迎学习',
                path: '/',
                collapsable: false, // 不折叠
                children: [
                    { title: "学前必读", path: "/" }
                ]
            },
            {
              title: "基础学习",
              path: '/handbook/ConditionalTypes',
              collapsable: false, // 不折叠
              children: [
                { title: "条件类型", path: "/handbook/ConditionalTypes" },
                { title: "泛型", path: "/handbook/Generics" }
              ],
            }
          ]
    }
}
```

对应的效果如下：

![](https://cdn.jsdelivr.net/gh/mqyqingfeng/picture/1639296236075-99fca73f-f45d-44a2-bb0c-58cf505da7b7.png)

## 5. 更换主题

现在基本的目录和导航功能已经实现，但如果我还想要加载 loading、切换动画、模式切换（暗黑模式）、返回顶部、评论等功能呢，为了简化开发成本，我们可以直接使用主题，这里使用的主题是 [vuepress-theme-rec](https://vuepress-theme-reco.recoluan.com/)：

现在我们安装 vuepress-theme-reco：

```shell
npm install vuepress-theme-reco --save-dev
# or
yarn add vuepress-theme-reco
```

然后在 `config.js` 里引用该主题：

```typescript
module.exports = {
  // ...
  theme: 'reco'
  // ...
}  
```

刷新一下页面，我们会发现一些细节的改变，比如加载时的 loading 动画、以及支持切换暗黑模式：

![](https://cdn.jsdelivr.net/gh/mqyqingfeng/picture/1639297143795-832bbd65-2c34-462d-8325-533421686b1c.png)

## 6. 添加文章信息

但我们也会发现，像条件类型这一篇文章，`条件类型（Conditional Types）` 竟然出现了两遍，这是因为这个主题自动提取了第一个大标题作为本文的标题，我们可以在每篇文章的 md 文件中添加一些信息修改：

```shell
---
title: 条件类型
author: 冴羽
date: '2021-12-12'
---
```

此时文章的效果如下：

![](https://cdn.jsdelivr.net/gh/mqyqingfeng/picture/1639297596590-acb0e8fa-8359-48d2-8e20-04682455bc18.png)

但如果你不想要标题、作者、时间这些信息呢，我们可以在样式里隐藏，这个稍后会讲到。

## 7. 设置语言

注意，上图的文章时间，我们写入的格式为 `2021-12-12` ，但是显示的是 `12/12/2021`，这是因为  VuePress 默认的 lang 为 `en-US`，我们修改一下 config.js：

```typescript
module.exports = {
  // ...
  locales: {
    '/': {
      lang: 'zh-CN'
    }
  },
  // ...
}  
```

可以发现时间换了一种展示方式：

![](https://cdn.jsdelivr.net/gh/mqyqingfeng/picture/1639298017860-d4cb3da1-a135-45fa-aaae-b67e7636ea29.png)

## 8. 开启目录结构

在原本的主题里，我们发现每篇文章的目录结构出现在左侧：

![](https://cdn.jsdelivr.net/gh/mqyqingfeng/picture/1639298449494-fc99c825-3804-4201-8315-58cf9e044e90.png)

而 vuepress-theme-reco 将原有的侧边栏的中的多级标题移出，生成子侧边栏，放在了页面的右侧，如果你要全局开启，可在页面 config.js 里设置开启：

```typescript
module.exports = {
  //...
  themeConfig: {
    subSidebar: 'auto'
  }
  //...
}
```

此时效果如下：

![](https://cdn.jsdelivr.net/gh/mqyqingfeng/picture/1639298620756-0017a498-138a-4847-9f1b-af676b2aca5e.png)

## 9. 修改主题颜色

VuePress 基于 Vue，所以主题色用的是 Vue 的绿色，然而 TypeScript 的官方色则是蓝色，那如何修改 VuePress 的主题色呢？

你可以创建一个 `.vuepress/styles/palette.styl` 文件，文件代码如下：

```css
$accentColor = #3178c6
```

此时可以发现主题颜色变了：

![](https://cdn.jsdelivr.net/gh/mqyqingfeng/picture/1639298906916-9e5202af-7bd1-463c-b675-8b25f574513f.png)

更多的颜色修改参考 VuePress 的 [palette.styl](https://vuepress.vuejs.org/zh/config/#palette-styl)。

## 10. 自定义修改样式

如果你想自定义修改一些 DOM 元素的样式呢？就比如在暗黑模式下：

![](https://cdn.jsdelivr.net/gh/mqyqingfeng/picture/1639299094766-80d0ebb5-a1eb-4890-98da-57428e9358ac.png)

我们发现用作强调的文字颜色比较暗淡，在暗黑模式下看不清楚，我想改下这个文字的颜色和背景色呢？

而 VuePress 提供了一种添加额外样式的简便方法。你可以创建一个 `.vuepress/styles/index.styl` 文件。这是一个 Stylus 文件，但你也可以使用正常的 CSS 语法。

我们在 .vupress 文件夹下创建这个目录，然后创建 index.styl 文件，代码如下：

```css
// 通过检查，查看元素样式声明
.dark .content__default code {
    background-color: rgba(58,58,92,0.7);
    color: #fff;
}
```

此时文字就清晰了很多：

![](https://cdn.jsdelivr.net/gh/mqyqingfeng/picture/1639299301715-15c10e03-3399-4a81-a4d1-f6bc4cbcf2b0.png)

那之前我们提到的隐藏每篇文章的标题、作者、时间呢，其实也是类似的方式：

```css
.page .page-title {
   display: none;
}
```

最后的效果如下：

![](https://cdn.jsdelivr.net/gh/mqyqingfeng/picture/1639299437767-129d288e-6d0f-4c9b-8d08-91a3ef3e9dae.png)

## 11. 部署

我们的博客就算是正式的做好了，接下来我们部署到免费的 Github Pages 上。我们在 Github 上新建一个仓库，这里我取得仓库名为：`learn-typescript`。

![](https://cdn.jsdelivr.net/gh/mqyqingfeng/picture/1639299860775-3b080ee5-1cc0-49a0-9771-a85d18900cd3.png)

对应，我们需要在 `config.js` 添加一个 `base` 路径配置：

```typescript
module.exports = {
  	// 路径名为 "/<REPO>/"
    base: '/learn-typescript/',
  	//...
}
```

最终的 `config.js` 文件内容为：

```typescript
module.exports = {
    title: 'TypeScript4 文档',
    description: 'TypeScript4 最新官方文档翻译',
    base: '/learn-typescript/',
    theme: 'reco',
    locales: {
        '/': {
          lang: 'zh-CN'
        }
    },
    themeConfig: {
        // lastUpdated: '上次更新',
        subSidebar: 'auto',
        nav: [
            { text: '首页', link: '/' },
            { 
                text: '冴羽的 JavaScript 博客', 
                items: [
                    { text: 'Github', link: 'https://github.com/mqyqingfeng' },
                    { text: '掘金', link: 'https://juejin.cn/user/712139234359182/posts' }
                ]
            }
        ],
        sidebar: [
            {
                title: '欢迎学习',
                path: '/',
                collapsable: false,
                children: [
                    { title: "学前必读", path: "/" }
                ]
            },
            {
              title: "基础学习",
              path: '/handbook/ConditionalTypes',
              collapsable: false,
              children: [
                { title: "条件类型", path: "/handbook/ConditionalTypes" },
                { title: "泛型", path: "/handbook/Generics" }
              ],
            }
          ]
    }
}
```

然后我们在项目 `vuepress-starter` 目录下建立一个脚本文件：`deploy.sh`，注意修改一下对应的用户名和仓库名：

```shell
#!/usr/bin/env sh

# 确保脚本抛出遇到的错误
set -e

# 生成静态文件
npm run docs:build

# 进入生成的文件夹
cd docs/.vuepress/dist

git init
git add -A
git commit -m 'deploy'

# 如果发布到 https://<USERNAME>.github.io/<REPO>
git push -f git@github.com:mqyqingfeng/learn-typescript.git master:gh-pages

cd -
```

然后命令行切换到 `vuepress-starter` 目录下，执行  `sh deploy.sh`，就会开始构建，然后提交到远程仓库，注意这里提交到了 `gh-pages` 分支，我们查看下对应仓库分支的代码：

![](https://cdn.jsdelivr.net/gh/mqyqingfeng/picture/1639300603158-74863664-99fc-4f1a-8d52-8dd57a3c81d5.png)

我们可以在仓库的 `Settings -> Pages` 中看到最后的地址：

![](https://cdn.jsdelivr.net/gh/mqyqingfeng/picture/1639300697456-37fb017c-062b-4106-b8f4-b032ec0475c4.png)

像我最后生成的地址就是 [https://mqyqingfeng.github.io/learn-typescript/](https://mqyqingfeng.github.io/learn-typescript/)

至此，我们完成了 VuePress 和 Github Pages 的部署。

## 系列文章

系列文章目录地址：[https://github.com/mqyqingfeng/Blog](https://github.com/mqyqingfeng/Blog)

微信：「mqyqingfeng」，加我进冴羽唯一的读者群。

如果有错误或者不严谨的地方，请务必给予指正，十分感谢。如果喜欢或者 有所启发，欢迎 star，对作者也是一种鼓励。

**Comment by FangzhouSu** [comment]
如果我想频繁更新我这个线上的文档 并且让他人也可以参与进来文档共建 是不是把vuepress-start这个文件夹都提到github上来最好呢？ 另外 感谢讶羽大大的分享！

**Comment by zxl7** [comment]
> 如果我想一起写下这个最好的我可以写下我呢？ 👆刚才试了一下，好像文档好像没有，那么只有那么一次打包npm运行：build一下再修改了么，或者是 感谢羽大的分享！

巧了，宝， 应该是克隆 master 分支到本地仓库，然后本地仓库打包出的gh-pages文件提PR 给原始仓库 gh-pages

**Comment by FangzhouSu** [comment]
> > 如果我想一起写下这个最好的我可以写下我呢？ 👆刚才试了一下，好像文档好像没有，那么只有那么一次打包npm运行：build一下再修改了么，或者是 感谢羽大的分享！
> 
> 巧了，宝， 应该是克隆 master 分支到本地仓库，然后本地仓库打包出的gh-pages文件提PR 给原始仓库 gh-pages

好巧！
这两天实践了一下 就 每更新一次 打包一下 然后初始化仓库 提交commit 然后git push -f强制覆盖远程仓库对应分支 （我取名叫 init-pages) 然后在线版本就更新了 虽然有点麻烦 但是也没啥问题😂

**Comment by Zhengqbbb** [comment]
期待到时候使用 Vuepress-next | 我摸爬滚打了一整年，到时候基建任务交给我hhhh

**Comment by Zhengqbbb** [comment]
如果不想 `-f` 强行推送的话可以有另一套shell脚本方案。
脚本思路：
1. clone 两份 同一仓库 代码，一份分支假设是 `main` 另一份分支切到`gh-pages`
2. 在mian中运行脚本把dist文件 `cp` 到另一个的仓库
3. `cd` 到另一个仓库，提交diff代码，还可以添加很多自定义的小创意

毕竟 `-f` 有风险，比如shell脚本中cd dist的操作不慎出现错误找不到路径，并且又没有添加`return 1`的话，还往下执行了，那么你的原仓库就有可能永久性被覆盖

**Comment by gmh-ally** [comment]
sh deploy.sh   sh  是要安装什么包吗

**Comment by Zhengqbbb** [comment]
> sh deploy.sh sh 是要安装什么包吗

你可以这么理解
- 所谓的脚本就是带有逻辑的命令集合文件。可以很方便的避免重复性工作（类比上面的发布过程），而sh就是使用shell来启动脚本文件的，类比package中定义script，你可以简单一句话就可以启动
- 而shell是大多数终端中自带的，所以不需要安装包
- ps：脚本逻辑也是有规范的比如shell遵循POSIXShell规范，恰恰windows的CMD和powershell不遵循，所以.sh脚本文件在windows寸步难行（类比你的js脚本文件使用python是无法运行的），所以建议windows用户安装WSL搭配windows-terminal使用

**Comment by xuxuejin** [comment]
整个项目是一个 git 仓库，执行 sh 脚本，在生成的 dist 目录种还要再初始化一个仓库，push 会报错，没法部署。

**Comment by Zhengqbbb** [comment]
> 整个项目是一个 git 仓库，执行 sh 脚本，在生成的 dist 目录种还要再初始化一个仓库，push 会报错，没法部署。

发一下脚本，或者仓库我可以看看

**Comment by xuxuejin** [comment]
我看了一下你的仓库，master 分支没有什么，gh-pages 分支是打包后的产物。我是想实现，master 是 vuePress的写作仓库，gh-pages是打包产物的仓库，这样 master 文档有版本管理，产物也有版本管理

**Comment by Zhengqbbb** [comment]
@xuxuejin 你说的是在一个存储库存在两份版本管理吗，这样应该不行
你需要两个存储库，用脚本来管理就可以
详情可以看我负责仓库 希望能帮助到你：
https://github.com/x-cmd/official-doc
https://github.com/x-cmd/official-website

**Comment by xuxuejin** [comment]
@Zhengqbbb 好的，谢谢你，我知道了

**Comment by AtroxEzerel** [comment]
有个问题请教一下
在本地执行npm run docs:dev后的页面是正常的
![image](https://user-images.githubusercontent.com/55567122/163711627-e36c60a1-04a9-4930-9575-56286709c1b4.png)
但是将代码提交到github.io之后出现了问题
![image](https://user-images.githubusercontent.com/55567122/163711652-70bf6549-94e6-46c3-962b-4c64478ee592.png)
地址https://atroxezerel.github.io/
请问这是什么问题  是哪里的配置不对吗？

**Comment by DrAugus** [comment]
大佬，Frontmatter-date，填充完不显示，是需要改什么配置吗？

**Comment by DrAugus** [comment]
> 大佬，Frontmatter-date，填充完不显示，是需要改什么配置吗？

默认的主题是没有此配置的。。。已经找到解决方案了。

**Comment by shyhhh** [comment]
羽哥 recv 主题的加载界面好像没有了

**Comment by shyhhh** [comment]
羽哥 reco 的加载界面好像没了

**Comment by yiting-sister** [comment]
引入主题的时候  Uncaught Error: Cannot find module '@theme/mixins/posts' 报错

**Comment by xiaojuan-xu** [comment]
赞赞

**Comment by rongweihe** [comment]
2023 最新，GitHub 在后面把默认的 master 分支改成了 main 分支，所以这里面的 master 应该改为 main ，不然会报错

git push -f git@github.com:mqyqingfeng/learn-typescript.git master:gh-pages

**Comment by hequan-Bill** [comment]
你好，想问一下在部署运行之后，但是在Github上的Pages却没有看到相对应的出现，这是什么原因呢

**Comment by lichengcan** [comment]
![Uploading image.png…]()
本地跑没有问题，build打包后就这样了，请问下有人知道是什么问题吗

**Comment by lichengcan** [comment]
![image](https://user-images.githubusercontent.com/82929061/230280138-7e45126a-0e5e-483a-80b5-1ca1475fb965.png)
本地跑没有问题，build打包后就这样了，请问下有人知道是什么问题吗

**Comment by lichengcan** [comment]
> ![image](https://user-images.githubusercontent.com/82929061/230280138-7e45126a-0e5e-483a-80b5-1ca1475fb965.png) 本地跑没有问题，build打包后就这样了，请问下有人知道是什么问题吗

部署后F12显示js找不到

**Comment by danghfz** [comment]
> ![image](https://user-images.githubusercontent.com/82929061/230280138-7e45126a-0e5e-483a-80b5-1ca1475fb965.png) 本地跑没有问题，build打包后就这样了，请问下有人知道是什么问题吗

这个是路径的问题，你仔细看base那个，或者查看打包的静态文件里面的js文件，css什么的路径都是错的

**Comment by wyz210052253** [comment]
> sh deploy.sh sh 是要安装什么包吗

win系统可以在电脑中安装git,然后在你项目根文件夹里面运行git命令行，执行sh deploy.sh也可以。需要你本地的git和github设置了ssh。

**Comment by Arthur253896** [comment]
为什么我部署到github上之后出现很多黑条，css路径没get到

**Comment by Arthur253896** [comment]
> > ![image](https://user-images.githubusercontent.com/82929061/230280138-7e45126a-0e5e-483a-80b5-1ca1475fb965.png) 本地跑没有问题，build打包后就这样了，请问下有人知道是什么问题吗
> 
> 部署后F12显示js找不到

请问解决了吗

**Comment by Arthur253896** [comment]
![image](https://user-images.githubusercontent.com/104065291/236612434-398ef77a-4154-4f60-92d5-f85f4544360b.png)
z这是为什么啊

**Comment by hph31** [comment]
> ![image](https://user-images.githubusercontent.com/104065291/236612434-398ef77a-4154-4f60-92d5-f85f4544360b.png) z这是为什么啊

可能是有档案放错位置，我之前是因为config.js没放进.vuepress

**Comment by dcj00** [comment]
> ![image](https://user-images.githubusercontent.com/82929061/230280138-7e45126a-0e5e-483a-80b5-1ca1475fb965.png) 本地跑没有问题，build打包后就这样了，请问下有人知道是什么问题吗

![image](https://github.com/mqyqingfeng/Blog/assets/30423445/f6ad0ccf-0bda-442f-97f1-4a82b0aa0807)
加上base配置

**Comment by Peter-hcz** [comment]
部署这一块看不懂有懂的大佬吗？

**Comment by labuladong** [comment]
谢谢大佬分享。遇到一个中文路径引用图片时失败的问题，可以参见 [这篇博客](https://segmentfault.com/a/1190000022275001) 解决。

**Comment by GreyFossssssss** [comment]
> 
我也是同样问题

**Comment by elvis-shiqi** [comment]
> ![image](https://user-images.githubusercontent.com/82929061/230280138-7e45126a-0e5e-483a-80b5-1ca1475fb965.png) 本地跑没有问题，build打包后就这样了，请问下有人知道是什么问题吗

需要设置base路径  /路径/  不然css，js文件地址都不对

**Comment by kequeen** [comment]
总感觉这种实现方式还是有点ugly

**Comment by Z-p-github** [comment]
感谢大佬

**Comment by c2mx** [comment]
https://ts.yayujs.com/  域名SSL证书过期了 :rotating_light:

**Comment by xtt-nora** [comment]
(undefined) assets/js/styles.d6073527.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/nora/update/vuepress-starter/node_modules/.pnpm/terser-webpack-plugin@1.4.5_webpack@4.47.0/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/nora/update/vuepress-starter/node_modules/.pnpm/terser-webpack-plugin@1.4.5_webpack@4.47.0/node_modules/terser-webpack-plugin/dist/index.js:160:259)
